/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.IOException;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.Executors;
import java.util.stream.Collectors;

import static java.lang.System.exit;

public class App {
    public static void main(String[] args) throws IOException {
        long statTime = System.currentTimeMillis();

        var cli = new ChunkyBoyoCli(args);
        var conf = cli.asConfiguration();
        var ec = Executors.newFixedThreadPool(10);
        var sb = new ReaderBoyo(conf, ec);
        var f = ec.submit(sb);

        try {
            var l = f.get();
            Printer.println("Wrote following files: %s", String.join(",", l));
            Printer.println("Took %d ms", System.currentTimeMillis() - statTime);
        } catch (InterruptedException | ExecutionException e) {
            throw new RuntimeException(e);
        } finally {
            ec.shutdown();
        }

        exit(0);

    }


}
